name: Run Unit Tests

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.[mM][dD]'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14.x, 17.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Use Node.JS ${{ matrix.node }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}
      - name: Run scripts
        run: |
          npm ci
          npm test